sudo: required
services: docker
dist: bionic
group: edge
language: python
matrix:
    include:
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.8"
          env: TOXENV=py38
        - python: "pypy3"
          env: TOXENV=pypy3
install:
    - pip install -r requirements-dev.txt
script:
    - tox -e ${TOXENV}
after_success:
    - coveralls
